"""
Academic / Research Prediction Summary Generator.
Creates structured prediction summaries for research review with mandatory non-clinical disclaimers.
"""

from typing import Dict, Any
from datetime import datetime
from src.data.validation import CLASS_DISPLAY_NAMES


def generate_academic_summary_text(
    image_name: str,
    model_name: str,
    predicted_class: str,
    confidence_scores: Dict[str, float],
    has_gradcam: bool = True
) -> str:
    """
    Generate an Academic & Research Prediction Summary string.
    
    Includes explicit notices stating that the application is an educational prototype and not a medical device.
    """
    now_str = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    disp_pred = CLASS_DISPLAY_NAMES.get(predicted_class, predicted_class)
    
    scores_formatted = "\n".join([
        f"  - {CLASS_DISPLAY_NAMES.get(cls, cls)}: {prob * 100:.2f}%"
        for cls, prob in confidence_scores.items()
    ])
    
    report = f"""================================================================================
EXPLAINABLE DEEP LEARNING ALZHEIMER'S MRI ANALYSIS - ACADEMIC RESEARCH SUMMARY
================================================================================

Date & Timestamp      : {now_str}
Analyzed Image File   : {image_name}
Evaluated Model       : {model_name}
Predicted Stage       : {disp_pred}
Grad-CAM Generated    : {'Yes (Visual heatmaps rendered)' if has_gradcam else 'No'}

--------------------------------------------------------------------------------
STAGE PROBABILITY DISTRIBUTION:
--------------------------------------------------------------------------------
{scores_formatted}

--------------------------------------------------------------------------------
METHODOLOGY & EXPLAINABILITY NOTES:
--------------------------------------------------------------------------------
1. Feature Attribution: Visual explanations are computed using Gradient-weighted
   Class Activation Mapping (Grad-CAM) targeting the final convolutional layer.
2. Heatmap Interpretation: Highlighted regions indicate spatial areas that
   positively contributed to the selected class logit.

--------------------------------------------------------------------------------
ACADEMIC & NON-CLINICAL DISCLAIMER:
--------------------------------------------------------------------------------
IMPORTANT NOTICE:
This summary is generated by an academic student research prototype developed
for computer vision and deep learning study. It is NOT a medical device, clinical
diagnostic report, or healthcare assessment. The predictions and heatmaps must
NOT be used for medical diagnosis, treatment recommendations, patient staging,
or clinical decision-making. Always consult qualified healthcare professionals
and radiologists for clinical evaluation.
================================================================================
"""
    return report
